version: "3"

services:
  regui:
    container_name: regui
    image: regui
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 9002:9002
    environment:
      - LISTEN_PORT=9002
      - REGISTRY_PORT=9001
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      ce_frontend:
        ipv4_address: 192.168.255.240

networks:
  ce_frontend:
    external: true

